# Generated by Django 3.0.4 on 2020-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
